version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: 9zapp.app
  ##login: admin
  #secure: always

#handlers:
#- url: /errorfinder/
#  script: 9zapp.app


libraries:
- name: webapp2
  version: latest
